// желательно добавить
// добавить функцию смены статистики играков каждую новую неделю

// это не так важно можно и не добовлять
// один раунд соревнований между игроками идет одну неделю по итого которой во вкладек
// соревнования  таблица в которой  остается 3 самых результативных игрока и видно дату начала и
// конца соревнований

const { User, Team, Player, TeamPlayer, sequelize } = require("./models");

async function seedDatabase() {
  try {
    console.log("Начало заполнения БД...");
    await TeamPlayer.destroy({ where: {} });
    await Team.destroy({ where: {} });
    await Player.destroy({ where: {} });
    await User.destroy({ where: {} });

    // const users = await User.bulkCreate([
    //   {
    //     name: "Admin",
    //     email: "admin@admin.com",
    //     password: "admin",
    //     role: "admin",
    //   },
    // {
    //   name: "Ивано Петров",
    //   email: "user@user.com",
    //   password: "user",
    // },
    // {
    //   name: "Мария Петрова",
    //   email: "user1@user.com",
    //   password: "user",
    // },
    // ]);
    // ВСЕ ИГРОКИ
    // const UNICS_KAZAN = [
    //   { name: 'Маркос Найт', points: 16.1, rebounds: 4.1, assists: 4.0, fouls: 2.4, steals: 1.6, turnovers: 2.1, blocks: 0.1, avatar: "/img/UNIKS/Маркос Найт.png", cost: 70 },
    //   { name: 'Девон Акун-Перселл', points: 15.8, rebounds: 3.1, assists: 3.2, fouls: 2.5, steals: 1.2, turnovers: 1.9, blocks: 0.3,avatar: "/img/UNIKS/Девон Акун-Перселл.png", cost: 65 },
    //   { name: 'Джален Рейнольдс', points: 14.3, rebounds: 5.9, assists: 1.9, fouls: 2.8, steals: 1.3, turnovers: 1.9, blocks: 0.7,avatar: "/img/UNIKS/Джален Рейнольдс.png", cost: 60 },
    //   { name: 'Маркус Кин', points: 10.3, rebounds: 2.3, assists: 2.7, fouls: 2.6, steals: 0.4, turnovers: 2.2, blocks: 0.0,avatar: "/img/UNIKS/Маркус Кин.png", cost: 45 },
    //   { name: 'Тони Тэйлор', points: 9.8, rebounds: 2.2, assists: 4.3, fouls: 2.2, steals: 1.0, turnovers: 1.0, blocks: 0.0,avatar: "/img/UNIKS/Тони Тэйлор.png", cost: 45 },
    //   { name: 'Исмаэль Бако', points: 9.0, rebounds: 6.8, assists: 0.8, fouls: 1.9, steals: 0.8, turnovers: 0.8, blocks: 1.2,avatar: "/img/UNIKS/Исмаэль Бако.png", cost: 50 },
    //   { name: 'Дарран Хиллиард', points: 8.9, rebounds: 1.8, assists: 1.4, fouls: 2.0, steals: 0.7, turnovers: 1.2, blocks: 0.0,avatar: "/img/UNIKS/Дарран Хиллиард.png", cost: 40 },
    //   { name: 'Дмитрий Кулагин', points: 6.5, rebounds: 2.7, assists: 3.5, fouls: 1.8, steals: 0.6, turnovers: 0.9, blocks: 0.1,avatar: "/img/UNIKS/Дмитрий Кулагин.png", cost: 35 },
    //   { name: 'Луи Лабери', points: 6.4, rebounds: 4.3, assists: 0.9, fouls: 0.7, steals: 0.3, turnovers: 0.4, blocks: 0.1,avatar: "/img/UNIKS/Луи Лабери.png", cost: 35 },
    //   { name: 'Андрей Лопатин', points: 6.3, rebounds: 3.1, assists: 1.4, fouls: 2.2, steals: 0.9, turnovers: 0.9, blocks: 0.2,avatar: "/img/UNIKS/Андрей Лопатин.png", cost: 30 },
    //   { name: 'Михаил Беленицкий', points: 5.5, rebounds: 3.8, assists: 1.3, fouls: 2.6, steals: 1.3, turnovers: 0.7, blocks: 0.2,avatar: "/img/UNIKS/Михаил Беленицкий.png", cost: 30 },
    //   { name: 'Сергей Торопов', points: 3.7, rebounds: 2.3, assists: 0.7, fouls: 1.9, steals: 0.5, turnovers: 0.6, blocks: 0.1,avatar: "/img/UNIKS/Сергей Торопов.png", cost: 20 },
    //   { name: 'Артем Комолов', points: 3.1, rebounds: 1.1, assists: 0.9, fouls: 1.4, steals: 0.4, turnovers: 0.3, blocks: 0.1,avatar: "/img/UNIKS/Артем Комолов.png", cost: 20 },
    //   { name: 'Александр Платунов', points: 1.9, rebounds: 0.5, assists: 1.2, fouls: 0.5, steals: 0.2, turnovers: 0.3, blocks: 0.0,avatar: "/img/UNIKS/Александр Платунов.png", cost: 15 },
    //   { name: 'Александр Стуленков', points: 1.3, rebounds: 0.9, assists: 0.2, fouls: 0.5, steals: 0.0, turnovers: 0.2, blocks: 0.0,avatar: "/img/UNIKS/Александр Стуленков.png", cost: 10 },
    //   { name: 'Роман Илюк', points: 1.3, rebounds: 0.4, assists: 0.6, fouls: 0.2, steals: 0.2, turnovers: 0.0, blocks: 0.0,avatar: "/img/UNIKS/Роман Илюк.png", cost: 10 },
    //   { name: 'Кит Лэнгфорд', points: 21.8, rebounds: 3.4, assists: 3.7, fouls: 1.8, steals: 0.8, turnovers: 2.4, blocks: 0.2,avatar: "/img/UNIKS/Кит Лэнгфорд.png", cost: 70 },
    //   { name: 'Артем Параховский', points: 11.3, rebounds: 5.1, assists: 0.4, fouls: 2.3, steals: 0.3, turnovers: 0.8, blocks: 1.2,avatar: "/img/UNIKS/Артем Параховский.png", cost:50 },
    //   { name: 'Хоаким Колом', points: 11.3, rebounds: 3.9, assists: 5.7, fouls: 1.0, steals: 0.6, turnovers: 2.5, blocks: 0.0,avatar: "/img/UNIKS/Хоаким Колом.png", cost: 50 },
    //   { name: 'Лэтэвиус Уильямс', points: 6.9, rebounds: 5.1, assists: 0.5, fouls: 2.7, steals: 0.3, turnovers: 0.8, blocks: 0.5,avatar: "/img/UNIKS/Лэтэвиус Уильямс.png", cost: 40 },
    // ];

    // const CSKA = await CSKA.bulkCreate([
    //   { name: "Мело Тримбл", points: 14.8, rebounds: 2.7, assists: 4.1, fouls: 2.1, steals: 1.6, turnovers: 1.9, blocks: 0.1,avatar: "/img/CSKA/Мело Тримбл.png", cost: 70},
    //   { name: "Алекса Аврамович", points: 12.1, rebounds: 2.8, assists: 3.3, fouls: 1.6, steals: 1.3, turnovers: 1.6, blocks: 0.1,avatar: "/img/CSKA/Алекса Аврамович.png", cost: 55},
    //   { name: "Каспер Уэйр", points: 11.1, rebounds: 1.9, assists: 3.2, fouls: 1.8, steals: 0.7, turnovers: 1.2, blocks: 0.0,avatar: "/img/CSKA/Каспер Уэйр.png",cost: 50  },
    //   { name: "Тони Джекири", points: 10.7, rebounds: 5.2, assists: 1.0, fouls: 2.1, steals: 0.7, turnovers: 0.9, blocks: 0.4,avatar: "/img/CSKA/Тони Джекири.png",cost: 45 },
    //   { name: "Амат Мбайе", points: 10.3, rebounds: 2.8, assists: 1.5, fouls: 1.8, steals: 0.9, turnovers: 1.3, blocks: 0.4,avatar: "/img/CSKA/Амат Мбайе.png",cost: 45 },
    //   { name: "Ливио Жан-Шарль", points: 10.1, rebounds: 4.1, assists: 1.1, fouls: 2.0, steals: 0.5, turnovers: 1.0, blocks: 0.5,avatar: "/img/CSKA/Ливио Жан-Шарль.png",cost: 45 },
    //   { name: "Антон Астапкович", points: 7.6, rebounds: 3.7, assists: 1.6, fouls: 1.7, steals: 0.8, turnovers: 1.1, blocks: 0.2,avatar: "/img/CSKA/Антон Астапкович.png",cost: 35 },
    //   { name: "Юрий Умрихин", points: 6.0, rebounds: 0.7, assists: 1.3, fouls: 1.3, steals: 0.0, turnovers: 0.7, blocks: 0.0,avatar: "/img/CSKA/Юрий Умрихин.png",cost: 25 },
    //   { name: "Иван Ухов", points: 5.4, rebounds: 2.9, assists: 2.0, fouls: 2.7, steals: 1.1, turnovers: 0.8, blocks: 0.1,avatar: "/img/CSKA/Иван Ухов.png",cost: 30 },
    //   { name: "Семен Антонов", points: 4.0, rebounds: 1.8, assists: 0.7, fouls: 1.7, steals: 0.4, turnovers: 0.3, blocks: 0.5,avatar: "/img/CSKA/Семен Антонов.png",cost: 25 },
    //   { name: "Никита Курбанов", points: 3.7, rebounds: 3.8, assists: 1.3, fouls: 1.6, steals: 0.5, turnovers: 0.5, blocks: 0.2,avatar: "/img/CSKA/Никита Курбанов.png",cost: 25 },
    //   { name: "Руслан Абдулбасиров", points: 3.4, rebounds: 1.6, assists: 0.4, fouls: 0.2, steals: 0.3, turnovers: 0.2, blocks: 0.4,avatar: "/img/CSKA/Руслан Абдулбасиров.png",cost: 20 },
    //   { name: "Владимир Карпенко", points: 3.1, rebounds: 0.7, assists: 0.9, fouls: 1.1, steals: 0.7, turnovers: 0.5, blocks: 0.0,avatar: "/img/CSKA/Владимир Карпенко.png",cost: 20 },
    //   { name: "Александр Ганькевич", points: 2.7, rebounds: 2.1, assists: 0.8, fouls: 1.4, steals: 0.2, turnovers: 0.5, blocks: 0.2,avatar: "/img/CSKA/Александр Ганькевич.png",cost: 20 },
    //   { name: "Никита Михайловский", points: 2.3, rebounds: 1.9, assists: 0.9, fouls: 1.0, steals: 0.0, turnovers: 0.3, blocks: 0.3,avatar: "/img/CSKA/Никита Михайловский.png",cost: 20 },
    //   { name: "Нандо Де Коло", points: 16.7, rebounds: 2.7, assists: 4.2, fouls: 2.7, steals: 1.2, turnovers: 2.6, blocks: 0.1,avatar: "/img/CSKA/Нандо Де Коло.png", cost: 75 },
    //   { name: "Серхио Родригес", points: 9.8, rebounds: 1.9, assists: 5.2, fouls: 1.9, steals: 0.9, turnovers: 1.7, blocks: 0.1,avatar: "/img/CSKA/Серхио Родригес.png",cost: 50 },
    //   { name: "Уилл Клайберн", points: 12.4, rebounds: 4.5, assists: 1.7, fouls: 2.5, steals: 0.6, turnovers: 0.9, blocks: 0.5,avatar: "/img/CSKA/Уилл Клайберн.png",cost: 55 },
    //   { name: "Отелло Хантер", points: 8.5, rebounds: 4.0, assists: 0.7, fouls: 2.3, steals: 0.7, turnovers: 0.5, blocks: 0.3,avatar: "/img/CSKA/Отелло Хантер.png",cost: 40 },
    //   { name: "Кайл Хайнс", points: 9.3, rebounds: 4.6, assists: 1.2, fouls: 2.0, steals: 0.9, turnovers: 1.0, blocks: 0.4,avatar: "/img/CSKA/Кайл Хайнс.png",cost: 45 },
    // ]);

    // const loko = [
    //   +{ name: "Патрик Миллер", points: 15.9, rebounds: 3.4, assists: 6.0, fouls: 2.4, steals: 1.5, turnovers: 2.6, blocks: 0.0,avatar: "/img/LOKO/Патрик Миллер.png", cost: 70 },
    //   +{ name: "Антониус Кливленд", points: 14.0, rebounds: 4.3, assists: 3.0, fouls: 2.3, steals: 1.7, turnovers: 2.0, blocks: 0.7,avatar: "/img/LOKO/Антониус Кливленд.png", cost: 65 },
    //   +{ name: "Би Джей Джонсон", points: 12.5, rebounds: 3.8, assists: 1.0, fouls: 2.0, steals: 1.0, turnovers: 1.6, blocks: 0.5,avatar: "/img/LOKO/Би Джей Джонсон.png", cost: 60 },
    //   { name: "Таджер Макколл", points: 10.3, rebounds: 2.4, assists: 3.2, fouls: 3.0, steals: 1.4, turnovers: 1.9, blocks: 0.2,avatar: "/img/LOKO/Таджер Макколл.png", cost: 50 },
    //   { name: "Карвел Андерсон", points: 8.3, rebounds: 2.2, assists: 0.9, fouls: 1.3, steals: 0.5, turnovers: 0.7, blocks: 0.0,avatar: "/img/LOKO/Карвел Андерсон.png", cost: 40 },
    //   { name: "Айзейя Уэйли", points: 8.1, rebounds: 5.2, assists: 0.9, fouls: 2.0, steals: 0.7, turnovers: 0.9, blocks: 1.1,avatar: "/img/LOKO/Айзейя Уэйли.png", cost: 45 },
    //   { name: "Андрей Мартюк", points: 8.1, rebounds: 4.9, assists: 1.0, fouls: 2.3, steals: 0.4, turnovers: 1.0, blocks: 0.6,avatar: "/img/LOKO/ндрей Мартюк.png", cost: 45 },
    //   { name: "Кирилл Елатонцев", points: 7.2, rebounds: 4.6, assists: 0.8, fouls: 2.3, steals: 0.5, turnovers: 0.8, blocks: 1.1,avatar: "/img/LOKO/Кирилл Елатонцев.png", cost: 40 },
    //   { name: "Владислав Емченко", points: 6.3, rebounds: 1.8, assists: 2.1, fouls: 1.7, steals: 0.8, turnovers: 1.1, blocks: 0.1,avatar: "/img/LOKO/Владислав Емченко.png", cost: 35 },
    //   { name: "Александр Гудумак", points: 5.7, rebounds: 1.8, assists: 0.8, fouls: 2.6, steals: 0.4, turnovers: 0.8, blocks: 0.2,avatar: "/img/LOKO/Александр Гудумак.png", cost: 35 },
    //   { name: "Кирилл Темиров", points: 5.6, rebounds: 1.7, assists: 1.2, fouls: 2.2, steals: 1.0, turnovers: 0.8, blocks: 0.1,avatar: "/img/LOKO/Кирилл Темиров.png", cost: 35 },
    //   { name: "Антон Квитковских", points: 4.6, rebounds: 2.7, assists: 0.8, fouls: 2.2, steals: 0.6, turnovers: 0.6, blocks: 0.3,avatar: "/img/LOKO/Антон Квитковских.png", cost: 30 },
    //   { name: "Михаил Ведищев", points: 4.3, rebounds: 0.9, assists: 1.7, fouls: 1.2, steals: 0.3, turnovers: 1.0, blocks: 0.0,avatar: "/img/LOKO/Михаил Ведищев.png", cost: 25 },
    //   { name: "Джон Дженкинс", points: 4.1, rebounds: 1.1, assists: 0.5, fouls: 1.1, steals: 0.1, turnovers: 0.4, blocks: 0.0,avatar: "/img/LOKO/Джон Дженкинс.png", cost: 25 },
    //   { name: "Данил Шеянов", points: 3.8, rebounds: 1.6, assists: 0.6, fouls: 1.6, steals: 0.5, turnovers: 0.4, blocks: 0.5,avatar: "/img/LOKO/Данил Шеянов.png", cost: 20 },
    //   { name: "Всеволод Ищенко", points: 3.2, rebounds: 1.5, assists: 1.2, fouls: 1.8, steals: 0.5, turnovers: 1.1, blocks: 0.1,avatar: "/img/LOKO/Всеволод Ищенко.png", cost: 20 },
    //   { name: "Дмитрий Узинский", points: 3.2, rebounds: 1.8, assists: 0.4, fouls: 1.9, steals: 0.5, turnovers: 0.3, blocks: 0.1,avatar: "/img/LOKO/Дмитрий Узинский.png", cost:20 },
    //   { name: "Даниил Коско", points: 1.2, rebounds: 0.5, assists: 0.8, fouls: 1.3, steals: 0.8, turnovers: 0.0, blocks: 0.2,avatar: "/img/LOKO/Даниил Коско.png", cost: 10 },
    //   -{ name: "Артем Чеваренков", points: 0.8, rebounds: 0.3, assists: 1.7, fouls: 0.7, steals: 0.7, turnovers: 0.8, blocks: 0.0,avatar: "/img/LOKO/Артем Чеваренков.png", cost: 10 },
    //   -{ name: "Джейлен Барфорд", points: 16.5, rebounds: 3.6, assists: 3.8, fouls: 2.4, steals: 1.6, turnovers: 2.1, blocks: 0.2,avatar: "/img/LOKO/Джейлен Барфорд.png", cost: 70 },
    // ];

    //  const ZENIT_PLAYERS = [
    //   +{ name: "Дуэйн Бэйкон", points: 17.6, rebounds: 3.2, assists: 2.2, fouls: 2.7, steals: 0.7, turnovers: 2.0, blocks: 0.2,avatar: "/img/ZENIT/Дуэйн Бэйкон.png", cost: 70 },
    //   +{ name: "Ксавьер Мун", points: 13.5, rebounds: 3.3, assists: 5.0, fouls: 1.9, steals: 1.2, turnovers: 2.2, blocks: 0.5,avatar: "/img/ZENIT/Ксавьер Мун.png", cost: 55 },
    //   +{ name: "Трент Фрейзер", points: 11.9, rebounds: 1.9, assists: 4.2, fouls: 2.3, steals: 0.9, turnovers: 1.8, blocks: 0.1,avatar: "/img/ZENIT/Трент Фрейзер.png", cost: 50 },
    //   +{ name: "Алекс Пойтресс", points: 9.8, rebounds: 3.1, assists: 0.4, fouls: 2.5, steals: 0.7, turnovers: 0.9, blocks: 0.9,avatar: "/img/ZENIT/Алекс Пойтресс.png", cost: 45 },
    //   +{ name: "Алексей Швед", points: 9.0, rebounds: 1.8, assists: 5.1, fouls: 1.7, steals: 0.5, turnovers: 1.8, blocks: 0.3,avatar: "/img/ZENIT/Алексей Швед.png", cost: 45 },
    //   +{ name: "Винс Хантер", points: 8.4, rebounds: 3.5, assists: 1.1, fouls: 2.6, steals: 1.1, turnovers: 0.9, blocks: 0.9,avatar: "/img/ZENIT/Винс Хантер.png", cost: 45 },
    //   +{ name: "Окаро Уайт", points: 7.7, rebounds: 2.6, assists: 0.9, fouls: 2.6, steals: 0.7, turnovers: 0.6, blocks: 0.2,avatar: "/img/ZENIT/Окаро Уайт.png", cost: 40 },
    //   +{ name: "Георгий Жбанов", points: 6.9, rebounds: 2.0, assists: 1.2, fouls: 2.3, steals: 1.3, turnovers: 0.6, blocks: 0.3,avatar: "/img/ZENIT/Георгий Жбанов.png", cost:35 },
    //   +{ name: "Сергей Карасев", points: 5.8, rebounds: 2.2, assists: 1.4, fouls: 2.1, steals: 1.0, turnovers: 0.3, blocks: 0.3,avatar: "/img/ZENIT/.png", cost: 30 },
    //   +{ name: "Андрей Воронцевич", points: 5.1, rebounds: 2.5, assists: 1.2, fouls: 1.7, steals: 0.6, turnovers: 0.4, blocks: 0.4,avatar: "/img/ZENIT/Сергей Карасев.png", cost: 30 },
    //   +{ name: "Александр Щербенев", points: 3.8, rebounds: 0.8, assists: 1.8, fouls: 1.0, steals: 0.4, turnovers: 0.7, blocks: 0.0,avatar: "/img/ZENIT/Александр Щербенев.png", cost: 20 },
    //   +{ name: "Егор Рыжов", points: 3.1, rebounds: 0.8, assists: 0.3, fouls: 1.2, steals: 0.2, turnovers: 0.6, blocks: 0.2,avatar: "/img/ZENIT/Егор Рыжов.png", cost: 15 },
    //   +{ name: "Денис Захаров", points: 2.3, rebounds: 0.7, assists: 0.3, fouls: 1.0, steals: 0.2, turnovers: 0.3, blocks: 0.0,avatar: "/img/ZENIT/Денис Захаров.png", cost:10 },
    //   +{ name: "Томас Эртель", points: 13.0, rebounds: 2.2, assists: 8.1, fouls: 2.2, steals: 1.0, turnovers: 3.1, blocks: 0.0,avatar: "/img/ZENIT/Томас Эртель.png", cost: 55 },
    //   +{ name: "Калеб Хоумсли", points: 11.2, rebounds: 2.9, assists: 1.9, fouls: 2.2, steals: 0.7, turnovers: 1.1, blocks: 0.3,avatar: "/img/ZENIT/Калеб Хоумсли.png", cost: 50 },
    //   +{ name: "Джордан Мики", points: 13.3, rebounds: 4.7, assists: 1.7, fouls: 2.4, steals: 1.0, turnovers: 1.5, blocks: 0.6,avatar: "/img/ZENIT/Джордан Мики.png", cost: 50 },
    //   +{ name: "Билли Бэрон", points: 14.1, rebounds: 1.5, assists: 2.3, fouls: 1.8, steals: 0.6, turnovers: 1.2, blocks: 0.0,avatar: "/img/ZENIT/Билли Бэрон.png", cost: 50 },
    //   { name: "Кевин Пангос", points: 12.5, rebounds: 1.8, assists: 6.8, fouls: 2.3, steals: 0.7, turnovers: 2.3, blocks: 0.0,avatar: "/img/ZENIT/Кевин Пангос.png", pcost: 50 },
    //   +{ name: "Джош Карлтон", points: 4.7, rebounds: 0.8, assists: 0.1, fouls: 1.3, steals: 0.1, turnovers: 1.3, blocks: 0.6,avatar: "/img/ZENIT/Джош Карлтон.png", cost:15 },
    //   +{ name: "Сергей Моня", points: 1.3, rebounds: 1.2, assists: 0.2, fouls: 0.2, steals: 0.2, turnovers: 0.2, blocks: 0.0,avatar: "/img/ZENIT/Сергей Моня.png", cost: 10 },
    // ];

    //ПОМЕНЯТЬ НАЗВАНИЯ СТАТИСТИКИ !!
    // ПОМЕНЯЛ НО ВСЕ СЛОМАЛОСЬ

    // {
    //   name: "Мело Тримбл",
    //   points: 14.8,
    //   rebounds: 2.7,
    //   assists: 4.1,
    //   fouls: 2.1,
    //   steals: 1.6,
    //   turnovers: 1.9,
    //   blocks: 0.1,
    //   avatar: "",
    //   cost: 95.0,
    // },
    // // price 120,
    // {
    //   name: "Алекса 1 Аврмович",
    //   points: 12.1,
    //   podboru: 2.8,
    //   peredachu: 3.3,
    //   folv: 1.6,
    //   perexvat: 1.3,
    //   poteri: 1.6,
    //   blokchotu: 0.1,
    //   avatar: "",
    //   cost: 95.0,
    // }, // 95
    const ALL_Playeres = await Player.bulkCreate([
      //  CSKA
      {
        name: "Мело Тримбл",
        position: "PG", // Разыгрывающий защитник
        points: 14.8,
        rebounds: 2.7,
        assists: 4.1,
        fouls: 2.1,
        steals: 1.6,
        turnovers: 1.9,
        blocks: 0.1,
        avatar: "/img/CSKA/Мело Тримбл.png",
        cost: 70,
      },
      {
        name: "Алекса Аврамович",
        position: "SG", // Атакующий защитник
        points: 12.1,
        rebounds: 2.8,
        assists: 3.3,
        fouls: 1.6,
        steals: 1.3,
        turnovers: 1.6,
        blocks: 0.1,
        avatar: "/img/CSKA/Алекса Аврамович.png",
        cost: 55,
      },
      {
        name: "Каспер Уэйр",
        position: "PG", // Разыгрывающий защитник
        points: 11.1,
        rebounds: 1.9,
        assists: 3.2,
        fouls: 1.8,
        steals: 0.7,
        turnovers: 1.2,
        blocks: 0.0,
        avatar: "/img/CSKA/Каспер Уэйр.png",
        cost: 50,
      },
      {
        name: "Тони Джекири",
        position: "C", // Центровой
        points: 10.7,
        rebounds: 5.2,
        assists: 1.0,
        fouls: 2.1,
        steals: 0.7,
        turnovers: 0.9,
        blocks: 0.4,
        avatar: "/img/CSKA/Тони Джекири.png",
        cost: 45,
      },
      {
        name: "Амат Мбайе",
        position: "PF", // Тяжёлый форвард
        points: 10.3,
        rebounds: 2.8,
        assists: 1.5,
        fouls: 1.8,
        steals: 0.9,
        turnovers: 1.3,
        blocks: 0.4,
        avatar: "/img/CSKA/Амат М'Бай.png",
        cost: 45,
      },
      {
        name: "Ливио Жан-Шарль",
        position: "PF", // Тяжёлый форвард
        points: 10.1,
        rebounds: 4.1,
        assists: 1.1,
        fouls: 2.0,
        steals: 0.5,
        turnovers: 1.0,
        blocks: 0.5,
        avatar: "/img/CSKA/Ливио Жан-Шарль.png",
        cost: 45,
      },
      {
        name: "Антон Астапкович",
        position: "SF", // Лёгкий форвард
        points: 7.6,
        rebounds: 3.7,
        assists: 1.6,
        fouls: 1.7,
        steals: 0.8,
        turnovers: 1.1,
        blocks: 0.2,
        avatar: "/img/CSKA/Антон Астапкович.png",
        cost: 35,
      },
      {
        name: "Юрий Умрихин",
        position: "PG", // Разыгрывающий защитник
        points: 6.0,
        rebounds: 0.7,
        assists: 1.3,
        fouls: 1.3,
        steals: 0.0,
        turnovers: 0.7,
        blocks: 0.0,
        avatar: "/img/CSKA/Юрий Умрихин.png",
        cost: 25,
      },
      {
        name: "Иван Ухов",
        position: "PG", // Разыгрывающий защитник
        points: 5.4,
        rebounds: 2.9,
        assists: 2.0,
        fouls: 2.7,
        steals: 1.1,
        turnovers: 0.8,
        blocks: 0.1,
        avatar: "/img/CSKA/Иван Ухов.png",
        cost: 30,
      },
      {
        name: "Семен Антонов",
        position: "PF", // Тяжёлый форвард
        points: 4.0,
        rebounds: 1.8,
        assists: 0.7,
        fouls: 1.7,
        steals: 0.4,
        turnovers: 0.3,
        blocks: 0.5,
        avatar: "/img/CSKA/Семён Антонов.png",
        cost: 25,
      },
      {
        name: "Никита Курбанов",
        position: "SF", // Лёгкий форвард
        points: 3.7,
        rebounds: 3.8,
        assists: 1.3,
        fouls: 1.6,
        steals: 0.5,
        turnovers: 0.5,
        blocks: 0.2,
        avatar: "/img/CSKA/Никита Курбанов.png",
        cost: 25,
      },
      {
        name: "Руслан Абдулбасиров",
        position: "SF", // Лёгкий форвард
        points: 3.4,
        rebounds: 1.6,
        assists: 0.4,
        fouls: 0.2,
        steals: 0.3,
        turnovers: 0.2,
        blocks: 0.4,
        avatar: "/img/CSKA/Руслан Абдулбасиров.png",
        cost: 20,
      },
      {
        name: "Владимир Карпенко",
        position: "PG", // Разыгрывающий защитник
        points: 3.1,
        rebounds: 0.7,
        assists: 0.9,
        fouls: 1.1,
        steals: 0.7,
        turnovers: 0.5,
        blocks: 0.0,
        avatar: "/img/CSKA/Владимир Карпенко.png",
        cost: 20,
      },
      {
        name: "Александр Ганькевич",
        position: "PF", // Тяжёлый форвард
        points: 2.7,
        rebounds: 2.1,
        assists: 0.8,
        fouls: 1.4,
        steals: 0.2,
        turnovers: 0.5,
        blocks: 0.2,
        avatar: "/img/CSKA/Александр Ганькевич.png",
        cost: 20,
      },
      {
        name: "Никита Михайловский",
        position: "SF", // Лёгкий форвард
        points: 2.3,
        rebounds: 1.9,
        assists: 0.9,
        fouls: 1.0,
        steals: 0.0,
        turnovers: 0.3,
        blocks: 0.3,
        avatar: "/img/CSKA/Никита Михайловский.png",
        cost: 20,
      },
      {
        name: "Нандо Де Коло",
        position: "SG", // Атакующий защитник
        points: 16.7,
        rebounds: 2.7,
        assists: 4.2,
        fouls: 2.7,
        steals: 1.2,
        turnovers: 2.6,
        blocks: 0.1,
        avatar: "/img/CSKA/Нандо Де Коло.png",
        cost: 75,
      },
      {
        name: "Серхио Родригес",
        position: "PG", // Разыгрывающий защитник
        points: 9.8,
        rebounds: 1.9,
        assists: 5.2,
        fouls: 1.9,
        steals: 0.9,
        turnovers: 1.7,
        blocks: 0.1,
        avatar: "/img/CSKA/Серхио Родригес.png",
        cost: 50,
      },
      {
        name: "Уилл Клайберн",
        position: "SF", // Лёгкий форвард
        points: 12.4,
        rebounds: 4.5,
        assists: 1.7,
        fouls: 2.5,
        steals: 0.6,
        turnovers: 0.9,
        blocks: 0.5,
        avatar: "/img/CSKA/Уилл Клайберн.png",
        cost: 55,
      },
      {
        name: "Отелло Хантер",
        position: "C", // Центровой
        points: 8.5,
        rebounds: 4.0,
        assists: 0.7,
        fouls: 2.3,
        steals: 0.7,
        turnovers: 0.5,
        blocks: 0.3,
        avatar: "/img/CSKA/Отелло Хантер.png",
        cost: 40,
      },
      {
        name: "Кайл Хайнс",
        position: "C", // Центровой
        points: 9.3,
        rebounds: 4.6,
        assists: 1.2,
        fouls: 2.0,
        steals: 0.9,
        turnovers: 1.0,
        blocks: 0.4,
        avatar: "/img/CSKA/Кайл Хайнс.png",
        cost: 45,
      },

      // ZENIT
      {
        name: "Дуэйн Бэйкон", //+
        position: "SF", // Лёгкий форвард
        points: 17.6,
        rebounds: 3.2,
        assists: 2.2,
        fouls: 2.7,
        steals: 0.7,
        turnovers: 2.0,
        blocks: 0.2,
        avatar: "/img/ZENIT/Дуэйн Бэйкон.png",
        cost: 70,
      },
      {
        name: "Ксавьер Мун",
        position: "PG", // Разыгрывающий защитник
        points: 13.5,
        rebounds: 3.3,
        assists: 5.0,
        fouls: 1.9,
        steals: 1.2,
        turnovers: 2.2,
        blocks: 0.5,
        avatar: "/img/ZENIT/Ксавьер Мун.png",
        cost: 55,
      },
      {
        name: "Трент Фрейзер",
        position: "SG", // Атакующий защитник
        points: 11.9,
        rebounds: 1.9,
        assists: 4.2,
        fouls: 2.3,
        steals: 0.9,
        turnovers: 1.8,
        blocks: 0.1,
        avatar: "/img/ZENIT/Трент Фрейзер.png",
        cost: 50,
      },
      {
        name: "Алекс Пойтресс", //+
        position: "PF", // Тяжёлый форвард
        points: 9.8,
        rebounds: 3.1,
        assists: 0.4,
        fouls: 2.5,
        steals: 0.7,
        turnovers: 0.9,
        blocks: 0.9,
        avatar: "/img/ZENIT/Алекс Пойтресс.png",
        cost: 45,
      },
      {
        name: "Алексей Швед", //+
        position: "SG", // Атакующий защитник
        points: 9.0,
        rebounds: 1.8,
        assists: 5.1,
        fouls: 1.7,
        steals: 0.5,
        turnovers: 1.8,
        blocks: 0.3,
        avatar: "/img/ZENIT/Алексей Швед.png",
        cost: 45,
      },
      {
        name: "Винс Хантер", //+
        position: "C", // Центровой
        points: 8.4,
        rebounds: 3.5,
        assists: 1.1,
        fouls: 2.6,
        steals: 1.1,
        turnovers: 0.9,
        blocks: 0.9,
        avatar: "/img/ZENIT/Винс Хантер.png",
        cost: 45,
      },
      {
        name: "Окаро Уайт", //+
        position: "PF", // Тяжёлый форвард
        points: 7.7,
        rebounds: 2.6,
        assists: 0.9,
        fouls: 2.6,
        steals: 0.7,
        turnovers: 0.6,
        blocks: 0.2,
        avatar: "/img/ZENIT/Окаро Уайт.png",
        cost: 40,
      },
      {
        name: "Георгий Жбанов", //+
        position: "SG", // Атакующий защитник
        points: 6.9,
        rebounds: 2.0,
        assists: 1.2,
        fouls: 2.3,
        steals: 1.3,
        turnovers: 0.6,
        blocks: 0.3,
        avatar: "/img/ZENIT/Георгий Жбанов.png",
        cost: 35,
      },
      {
        name: "Сергей Карасев",
        position: "SF", // Лёгкий форвард
        points: 5.8,
        rebounds: 2.2,
        assists: 1.4,
        fouls: 2.1,
        steals: 1.0,
        turnovers: 0.3,
        blocks: 0.3,
        avatar: "/img/ZENIT/Сергей Карасев.png",
        cost: 30,
      },
      {
        name: "Андрей Воронцевич", //+
        position: "PF", // Тяжёлый форвард
        points: 5.1,
        rebounds: 2.5,
        assists: 1.2,
        fouls: 1.7,
        steals: 0.6,
        turnovers: 0.4,
        blocks: 0.4,
        avatar: "/img/ZENIT/Андрей Воронцевич.png",
        cost: 30,
      },
      {
        name: "Александр Щербенев", //+
        position: "PG", // Разыгрывающий защитник
        points: 3.8,
        rebounds: 0.8,
        assists: 1.8,
        fouls: 1.0,
        steals: 0.4,
        turnovers: 0.7,
        blocks: 0.0,
        avatar: "/img/ZENIT/Александр Щербенев.png",
        cost: 20,
      },
      {
        name: "Егор Рыжов",
        position: "SG", // Атакующий защитник
        points: 3.1,
        rebounds: 0.8,
        assists: 0.3,
        fouls: 1.2,
        steals: 0.2,
        turnovers: 0.6,
        blocks: 0.2,
        avatar: "/img/ZENIT/Егор Рыжов.png",
        cost: 15,
      },
      {
        name: "Денис Захаров", //+
        position: "PG", // Разыгрывающий защитник
        points: 2.3,
        rebounds: 0.7,
        assists: 0.3,
        fouls: 1.0,
        steals: 0.2,
        turnovers: 0.3,
        blocks: 0.0,
        avatar: "/img/ZENIT/Денис Захаров.png",
        cost: 10,
      },
      {
        name: "Томас Эртель",
        position: "PG", // Разыгрывающий защитник
        points: 13.0,
        rebounds: 2.2,
        assists: 8.1,
        fouls: 2.2,
        steals: 1.0,
        turnovers: 3.1,
        blocks: 0.0,
        avatar: "/img/ZENIT/Томас Эртель.png",
        cost: 55,
      },
      {
        name: "Калеб Хоумсли",
        position: "SF", // Лёгкий форвард
        points: 11.2,
        rebounds: 2.9,
        assists: 1.9,
        fouls: 2.2,
        steals: 0.7,
        turnovers: 1.1,
        blocks: 0.3,
        avatar: "/img/ZENIT/Калеб Хоумсли.png",
        cost: 50,
      },
      {
        name: "Джордан Мики", //+
        position: "PF", // Тяжёлый форвард
        points: 13.3,
        rebounds: 4.7,
        assists: 1.7,
        fouls: 2.4,
        steals: 1.0,
        turnovers: 1.5,
        blocks: 0.6,
        avatar: "/img/ZENIT/Джордан Мики.png",
        cost: 50,
      },
      {
        name: "Билли Бэрон", //+
        position: "SG", // Атакующий защитник
        points: 14.1,
        rebounds: 1.5,
        assists: 2.3,
        fouls: 1.8,
        steals: 0.6,
        turnovers: 1.2,
        blocks: 0.0,
        avatar: "/img/ZENIT/Билли Бэрон.png",
        cost: 50,
      },
      {
        name: "Кевин Пангос",
        position: "PG", // Разыгрывающий защитник
        points: 12.5,
        rebounds: 1.8,
        assists: 6.8,
        fouls: 2.3,
        steals: 0.7,
        turnovers: 2.3,
        blocks: 0.0,
        avatar: "/img/ZENIT/Кевин Пангос.png",
        cost: 50,
      },
      {
        name: "Джош Карлтон",
        position: "C", // Центровой
        points: 4.7,
        rebounds: 0.8,
        assists: 0.1,
        fouls: 1.3,
        steals: 0.1,
        turnovers: 1.3,
        blocks: 0.6,
        avatar: "/img/ZENIT/Джош Карлтон.png",
        cost: 15,
      },
      {
        name: "Сергей Моня",
        position: "PF", // Тяжёлый форвард
        points: 1.3,
        rebounds: 1.2,
        assists: 0.2,
        fouls: 0.2,
        steals: 0.2,
        turnovers: 0.2,
        blocks: 0.0,
        avatar: "/img/ZENIT/Сергей Моня.png",
        cost: 10,
      },
      // LOKO

      {
        name: "Патрик Миллер", //+
        position: "PG",
        points: 15.9,
        rebounds: 3.4,
        assists: 6.0,
        fouls: 2.4,
        steals: 1.5,
        turnovers: 2.6,
        blocks: 0.0,
        avatar: "/img/LOKO/Патрик Миллер.png",
        cost: 70,
      },
      {
        name: "Антониус Кливленд", //+
        position: "SG/SF",
        points: 14.0,
        rebounds: 4.3,
        assists: 3.0,
        fouls: 2.3,
        steals: 1.7,
        turnovers: 2.0,
        blocks: 0.7,
        avatar: "/img/LOKO/Антониус Кливленд.png",
        cost: 65,
      },
      {
        name: "Би Джей Джонсон", //+
        position: "SF",
        points: 12.5,
        rebounds: 3.8,
        assists: 1.0,
        fouls: 2.0,
        steals: 1.0,
        turnovers: 1.6,
        blocks: 0.5,
        avatar: "/img/LOKO/Би Джей Джонсон.png",
        cost: 60,
      },
      {
        name: "Таджер Макколл", //+
        position: "SG",
        points: 10.3,
        rebounds: 2.4,
        assists: 3.2,
        fouls: 3.0,
        steals: 1.4,
        turnovers: 1.9,
        blocks: 0.2,
        avatar: "/img/LOKO/Таджер Макколл.png",
        cost: 50,
      },
      {
        name: "Карвел Андерсон", //+
        position: "SG",
        points: 8.3,
        rebounds: 2.2,
        assists: 0.9,
        fouls: 1.3,
        steals: 0.5,
        turnovers: 0.7,
        blocks: 0.0,
        avatar: "/img/LOKO/Карвел Андерсон.png",
        cost: 40,
      },
      {
        name: "Айзейя Уэйли", //+
        position: "PF",
        points: 8.1,
        rebounds: 5.2,
        assists: 0.9,
        fouls: 2.0,
        steals: 0.7,
        turnovers: 0.9,
        blocks: 1.1,
        avatar: "/img/LOKO/Айзейя Уэйли.png",
        cost: 45,
      },
      {
        name: "Андрей Мартюк", //+
        position: "PF/C",
        points: 8.1,
        rebounds: 4.9,
        assists: 1.0,
        fouls: 2.3,
        steals: 0.4,
        turnovers: 1.0,
        blocks: 0.6,
        avatar: "/img/LOKO/Андрей Мартюк.png", //+
        cost: 45,
      },
      {
        name: "Кирилл Елатонцев", //+
        position: "C",
        points: 7.2,
        rebounds: 4.6,
        assists: 0.8,
        fouls: 2.3,
        steals: 0.5,
        turnovers: 0.8,
        blocks: 1.1,
        avatar: "/img/LOKO/Кирилл Елатонцев.png",
        cost: 40,
      },
      {
        name: "Владислав Емченко", //+
        position: "PG",
        points: 6.3,
        rebounds: 1.8,
        assists: 2.1,
        fouls: 1.7,
        steals: 0.8,
        turnovers: 1.1,
        blocks: 0.1,
        avatar: "/img/LOKO/Владислав Емченко.png",
        cost: 35,
      },
      {
        name: "Александр Гудумак", //+
        position: "PF",
        points: 5.7,
        rebounds: 1.8,
        assists: 0.8,
        fouls: 2.6,
        steals: 0.4,
        turnovers: 0.8,
        blocks: 0.2,
        avatar: "/img/LOKO/Александр Гудумак.png",
        cost: 35,
      },
      {
        name: "Кирилл Темиров", //+
        position: "SG",
        points: 5.6,
        rebounds: 1.7,
        assists: 1.2,
        fouls: 2.2,
        steals: 1.0,
        turnovers: 0.8,
        blocks: 0.1,
        avatar: "/img/LOKO/Кирилл Темиров.png",
        cost: 35,
      },
      {
        name: "Антон Квитковских", //+
        position: "PF",
        points: 4.6,
        rebounds: 2.7,
        assists: 0.8,
        fouls: 2.2,
        steals: 0.6,
        turnovers: 0.6,
        blocks: 0.3,
        avatar: "/img/LOKO/Антон Квитковских.png",
        cost: 30,
      },
      {
        name: "Михаил Ведищев", //+
        position: "PG",
        points: 4.3,
        rebounds: 0.9,
        assists: 1.7,
        fouls: 1.2,
        steals: 0.3,
        turnovers: 1.0,
        blocks: 0.0,
        avatar: "/img/LOKO/Михаил Ведищев.png",
        cost: 25,
      },
      {
        name: "Джон Дженкинс", //+
        position: "SG",
        points: 4.1,
        rebounds: 1.1,
        assists: 0.5,
        fouls: 1.1,
        steals: 0.1,
        turnovers: 0.4,
        blocks: 0.0,
        avatar: "/img/LOKO/Джон Дженкинс.png",
        cost: 25,
      },
      {
        name: "Данил Шеянов", //+
        position: "SF",
        points: 3.8,
        rebounds: 1.6,
        assists: 0.6,
        fouls: 1.6,
        steals: 0.5,
        turnovers: 0.4,
        blocks: 0.5,
        avatar: "/img/LOKO/Данил Шеянов.png",
        cost: 20,
      },
      {
        name: "Всеволод Ищенко", //+
        position: "PG",
        points: 3.2,
        rebounds: 1.5,
        assists: 1.2,
        fouls: 1.8,
        steals: 0.5,
        turnovers: 1.1,
        blocks: 0.1,
        avatar: "/img/LOKO/Всеволод Ищенко.png",
        cost: 20,
      },
      {
        name: "Дмитрий Узинский", //+
        position: "PF",
        points: 3.2,
        rebounds: 1.8,
        assists: 0.4,
        fouls: 1.9,
        steals: 0.5,
        turnovers: 0.3,
        blocks: 0.1,
        avatar: "/img/LOKO/Дмитрий Узинский.png",
        cost: 20,
      },
      {
        name: "Даниил Коско", //+
        position: "PG",
        points: 1.2,
        rebounds: 0.5,
        assists: 0.8,
        fouls: 1.3,
        steals: 0.8,
        turnovers: 0.0,
        blocks: 0.2,
        avatar: "/img/LOKO/Даниил Коско.png",
        cost: 10,
      },
      {
        name: "Артем Чеваренков",
        position: "PG",
        points: 0.8,
        rebounds: 0.3,
        assists: 1.7,
        fouls: 0.7,
        steals: 0.7,
        turnovers: 0.8,
        blocks: 0.0,
        avatar: "/img/LOKO/Артем Чеваренков.png",
        cost: 10,
      },
      {
        name: "Джейлен Барфорд",
        position: "SG",
        points: 16.5,
        rebounds: 3.6,
        assists: 3.8,
        fouls: 2.4,
        steals: 1.6,
        turnovers: 2.1,
        blocks: 0.2,
        avatar: "/img/LOKO/Джейлен Барфорд.png",
        cost: 70,
      },
      // UNIKS

      {
        name: "Маркос Найт",
        position: "SG",
        points: 16.1,
        rebounds: 4.1,
        assists: 4.0,
        fouls: 2.4,
        steals: 1.6,
        turnovers: 2.1,
        blocks: 0.1,
        avatar: "/img/UNIKS/Маркос Найт.png",
        cost: 70,
      },
      {
        name: "Девон Акун-Перселл",
        position: "SF",
        points: 15.8,
        rebounds: 3.1,
        assists: 3.2,
        fouls: 2.5,
        steals: 1.2,
        turnovers: 1.9,
        blocks: 0.3,
        avatar: "/img/UNIKS/Девон Акун-Перселл.png",
        cost: 65,
      },
      {
        name: "Джален Рейнольдс",
        position: "C",
        points: 14.3,
        rebounds: 5.9,
        assists: 1.9,
        fouls: 2.8,
        steals: 1.3,
        turnovers: 1.9,
        blocks: 0.7,
        avatar: "/img/UNIKS/Джален Рейнольдс.png",
        cost: 60,
      },
      {
        name: "Маркус Кин",
        position: "PG",
        points: 10.3,
        rebounds: 2.3,
        assists: 2.7,
        fouls: 2.6,
        steals: 0.4,
        turnovers: 2.2,
        blocks: 0.0,
        avatar: "/img/UNIKS/Маркус Кин.png",
        cost: 45,
      },
      {
        name: "Тони Тэйлор",
        position: "PG",
        points: 9.8,
        rebounds: 2.2,
        assists: 4.3,
        fouls: 2.2,
        steals: 1.0,
        turnovers: 1.0,
        blocks: 0.0,
        avatar: "/img/UNIKS/Тони Тейлор.png",
        cost: 45,
      },
      {
        name: "Исмаэль Бако",
        position: "C",
        points: 9.0,
        rebounds: 6.8,
        assists: 0.8,
        fouls: 1.9,
        steals: 0.8,
        turnovers: 0.8,
        blocks: 1.2,
        avatar: "/img/UNIKS/Исмаэль Бако.png",
        cost: 50,
      },
      {
        name: "Дарран Хиллиард",
        position: "SG",
        points: 8.9,
        rebounds: 1.8,
        assists: 1.4,
        fouls: 2.0,
        steals: 0.7,
        turnovers: 1.2,
        blocks: 0.0,
        avatar: "/img/UNIKS/Дарран Хиллиард.png",
        cost: 40,
      },
      {
        name: "Дмитрий Кулагин",
        position: "PG",
        points: 6.5,
        rebounds: 2.7,
        assists: 3.5,
        fouls: 1.8,
        steals: 0.6,
        turnovers: 0.9,
        blocks: 0.1,
        avatar: "/img/UNIKS/Дмитрий Кулагин.png",
        cost: 35,
      },
      {
        name: "Луи Лабери",
        position: "PF",
        points: 6.4,
        rebounds: 4.3,
        assists: 0.9,
        fouls: 0.7,
        steals: 0.3,
        turnovers: 0.4,
        blocks: 0.1,
        avatar: "/img/UNIKS/Луи Лабери.png",
        cost: 35,
      },
      {
        name: "Андрей Лопатин",
        position: "PF",
        points: 6.3,
        rebounds: 3.1,
        assists: 1.4,
        fouls: 2.2,
        steals: 0.9,
        turnovers: 0.9,
        blocks: 0.2,
        avatar: "/img/UNIKS/Андрей Лопатин.png",
        cost: 30,
      },
      {
        name: "Михаил Беленицкий",
        position: "SF",
        points: 5.5,
        rebounds: 3.8,
        assists: 1.3,
        fouls: 2.6,
        steals: 1.3,
        turnovers: 0.7,
        blocks: 0.2,
        avatar: "/img/UNIKS/Михаил Беленицкий.png",
        cost: 30,
      },
      {
        name: "Сергей Торопов",
        position: "PF",
        points: 3.7,
        rebounds: 2.3,
        assists: 0.7,
        fouls: 1.9,
        steals: 0.5,
        turnovers: 0.6,
        blocks: 0.1,
        avatar: "/img/UNIKS/Сергей Торопов.png",
        cost: 20,
      },
      {
        name: "Артем Комолов",
        position: "SG",
        points: 3.1,
        rebounds: 1.1,
        assists: 0.9,
        fouls: 1.4,
        steals: 0.4,
        turnovers: 0.3,
        blocks: 0.1,
        avatar: "/img/UNIKS/Артем Комолов.png",
        cost: 20,
      },
      {
        name: "Александр Платунов",
        position: "PG",
        points: 1.9,
        rebounds: 0.5,
        assists: 1.2,
        fouls: 0.5,
        steals: 0.2,
        turnovers: 0.3,
        blocks: 0.0,
        avatar: "/img/UNIKS/Александр Платунов.png",
        cost: 15,
      },
      {
        name: "Александр Стуленков",
        position: "C",
        points: 1.3,
        rebounds: 0.9,
        assists: 0.2,
        fouls: 0.5,
        steals: 0.0,
        turnovers: 0.2,
        blocks: 0.0,
        avatar: "/img/UNIKS/Александр Стуленков.png",
        cost: 10,
      },
      {
        name: "Роман Илюк",
        position: "PG",
        points: 1.3,
        rebounds: 0.4,
        assists: 0.6,
        fouls: 0.2,
        steals: 0.2,
        turnovers: 0.0,
        blocks: 0.0,
        avatar: "/img/UNIKS/Роман Илюк.png",
        cost: 10,
      },
      {
        name: "Лэнгфорд Кит",
        position: "SG",
        points: 21.8,
        rebounds: 3.4,
        assists: 3.7,
        fouls: 1.8,
        steals: 0.8,
        turnovers: 2.4,
        blocks: 0.2,
        avatar: "/img/UNIKS/Лэнгфорд Кит.png",
        cost: 70,
      },
      {
        name: "Артём Параховский",
        position: "C",
        points: 11.3,
        rebounds: 5.1,
        assists: 0.4,
        fouls: 2.3,
        steals: 0.3,
        turnovers: 0.8,
        blocks: 1.2,
        avatar: "/img/UNIKS/Артём Параховский.png",
        cost: 50,
      },
      {
        name: "Колом Хоаким",
        position: "PG",
        points: 11.3,
        rebounds: 3.9,
        assists: 5.7,
        fouls: 1.0,
        steals: 0.6,
        turnovers: 2.5,
        blocks: 0.0,
        avatar: "/img/UNIKS/Колом Хоаким.png",
        cost: 50,
      },
      {
        name: "Уильямс Лэтэвиус",
        position: "PF",
        points: 6.9,
        rebounds: 5.1,
        assists: 0.5,
        fouls: 2.7,
        steals: 0.3,
        turnovers: 0.8,
        blocks: 0.5,
        avatar: "/img/UNIKS/Уильямс Лэтэвиус.png",
        cost: 40,
      },
    ]);

    // const team1 = await Team.create({
    //   name: "asdfasf",
    //   user_id: users[1].id,
    //   logo: "",
    //   total_points: 180.5,
    // });

    // const team2 = await Team.create({
    //   name: "qwe",
    //   user_id: users[2].id,
    //   logo: "",
    //   total_points: 130.5,
    // });

    await team1.addPlayers([players[0], players[1]]);
    await team2.addPlayers([players[2]]);

    console.log("Тестовые данные добавлены!");
  } catch (error) {
    console.error(error);
  } finally {
    await sequelize.close();
  }
}
//

seedDatabase();
// const team2 = await Team.create([
//     name: 'asdfasf',
//     user_id: 1,
//     logo: ''
// ])

// const team3 = await Team.create([
//     name: 'asdfasf',
//     user_id: 1,
//     logo: ''
// ])
